In [12]:
import os
import pandas as pd

In [13]:
comparison = []

In [26]:
folder = "tabula-extracted-csv/"
for f in os.scandir(folder):
    print(f.name) #printing all found csv files
    r = open(folder + f.name)
    
    if "Tolga" in f.name: #getting only one csv turned into dataframe
        tab = pd.read_csv(r, names=['key','value','x','xx'], header=None)

tabula-NOR_Bodo_20_51-08_3-75.csv
tabula-NOR_Asen_IL__Rotterudmoen__Nannestad_20_45-01_1-4.csv
tabula-NOR_Bodo_20_51-09_5-0.csv
tabula-NOR_Hoydalsmo_20_46-02_1-7.csv
tabula-NOR_Tolga_20_16-04_2-5.csv
tabula-NOR_Asen_IL__Rotterudmoen__Nannestad_20_45-05_5-0.csv

In [27]:
tab #looking at read dataframe

,key,value,x,xx
0,(1) Registration number:,20/16.04/2.5,NaN,NaN
1,(2) Name of the competition site:,Tolga,NaN,NaN
2,(3) Name of city/region:,Tolga/Hedmark Skikrets,NaN,NaN
3,(4) Organizer:,Tolga Idrettslag,NaN,NaN
4,(5) National ski association:,Norwegian Ski Federation,NaN,NaN
5,(6) Contact person in the organizing committee:,Paul Brennmoen,NaN,NaN
6,(7) Homologation inspector:,John Aalberg,NaN,NaN
7,(8) Name of course:,"2,5 km",NaN,NaN
8,(9) Competition level for course,COC,NaN,NaN
9,"Course length: 2,710m",Height difference (HD): 52m,Lowest point:,557m
10,Course category: D,Maximum climb (MC): 31m,Highest point:,609m
11,NaN,Total climb (TC): 89m,NaN,NaN
12,Date of Issue,NaN,NaN,NaN
13,09.04.2020,NaN,NaN,NaN
14,Valid until,NaN,NaN,NaN
15,30.06.2025,NaN,NaN,NaN

Not exactly as wanted, hard to read at some places, we can have a look at what works

In [20]:
tab[0:8]

,(1) Registration number:,20/16.04/2.5,Unnamed: 2,Unnamed: 3
0,(2) Name of the competition site:,Tolga,NaN,NaN
1,(3) Name of city/region:,Tolga/Hedmark Skikrets,NaN,NaN
2,(4) Organizer:,Tolga Idrettslag,NaN,NaN
3,(5) National ski association:,Norwegian Ski Federation,NaN,NaN
4,(6) Contact person in the organizing committee:,Paul Brennmoen,NaN,NaN
5,(7) Homologation inspector:,John Aalberg,NaN,NaN
6,(8) Name of course:,"2,5 km",NaN,NaN
7,(9) Competition level for course,COC,NaN,NaN

This seems fine and readable, so the problem is with the next lines, this could potentially be fixed by changing the tabula template used to read the files

In [28]:
tab[9:]

                      key                        value               x    xx
9   Course length: 2,710m  Height difference (HD): 52m   Lowest point:  557m
10     Course category: D      Maximum climb (MC): 31m  Highest point:  609m
11                    NaN        Total climb (TC): 89m             NaN   NaN
12          Date of Issue                          NaN             NaN   NaN
13             09.04.2020                          NaN             NaN   NaN
14            Valid until                          NaN             NaN   NaN
15             30.06.2025                          NaN             NaN   NaN

Trying to see if changing the csv manually solves our problems

In [42]:
fixed = open(folder + "fixed_tolga.csv")
tab_f = pd.read_csv(fixed,names=["key","value","x","xx"], header=None)

In [43]:
tab_f

,key,value,x,xx
0,(1) Registration number:,20/16.04/2.5,NaN,NaN
1,(2) Name of the competition site:,Tolga,NaN,NaN
2,(3) Name of city/region:,Tolga/Hedmark Skikrets,NaN,NaN
3,(4) Organizer:,Tolga Idrettslag,NaN,NaN
4,(5) National ski association:,Norwegian Ski Federation,NaN,NaN
5,(6) Contact person in the organizing committee:,Paul Brennmoen,NaN,NaN
6,(7) Homologation inspector:,John Aalberg,NaN,NaN
7,(8) Name of course:,"2,5 km",NaN,NaN
8,(9) Competition level for course,COC,NaN,NaN
9,Course length:,2,710m,NaN
10,Height difference (HD):,52m,NaN,NaN
11,Lowest point:,557m,NaN,NaN
12,Course category:,D,NaN,NaN
13,Maximum climb (MC):,31m,NaN,NaN
14,Highest point:,609m,NaN,NaN
15,Total climb (TC):,89m,NaN,NaN
16,Date of Issue,09.04.2020,NaN,NaN
17,Valid until,30.06.2025,NaN,NaN

In [44]:
tab_f = tab_f.dropna(axis="columns", how="any")

In [45]:
tab_f

                                                key                     value
0                          (1) Registration number:              20/16.04/2.5
1                 (2) Name of the competition site:                     Tolga
2                          (3) Name of city/region:    Tolga/Hedmark Skikrets
3                                    (4) Organizer:          Tolga Idrettslag
4                     (5) National ski association:  Norwegian Ski Federation
5   (6) Contact person in the organizing committee:            Paul Brennmoen
6                       (7) Homologation inspector:              John Aalberg
7                               (8) Name of course:                    2,5 km
8                  (9) Competition level for course                       COC
9                                    Course length:                         2
10                          Height difference (HD):                       52m
11                                    Lowest point:                      557m
12                                 Course category:                         D
13                              Maximum climb (MC):                       31m
14                                   Highest point:                      609m
15                                Total climb (TC):                       89m
16                                    Date of Issue                09.04.2020
17                                      Valid until                30.06.2025

---------
Manual comparison w/ google pinpoint gave following results with 69 sample pdfs:
Competition category:
(+x notation shows how many docments had to be read manually to retrieve actual category)
- D (39 + 1)
- E (19 + 1)
- C (7)
- E(D) (2)